<%@ Language="C#" Inherits="EnterDataPage.EnterDataClass" CodeFile="EnterData.aspx.cs" %>

<html>

    <head>
        <title>:: Enter Data ::</title>
        <link href="/style/style.css" rel="stylesheet" type="text/css">
        <script language="javascript" type="text/javascript" src="scripts/EnterDataScript.js"> </script>
    </head>

    <body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#E0E0E0" onload=" document.frmIdx.UrgentNote.disabled = true; ">
        <table width="570" border="0" cellpadding="0" cellspacing="0">
            <form name="frmIdx" action="EnterData.aspx" method="post" enctype="multipart/form-data" runat="server">
                <tr height="8"><td colspan="4"></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Last Name:</td><td width="10">&nbsp;</td><td width="380" class="textform"><input type="text" runat="server" ID="LastName" class="textform"><img src="/images/blank.gif" style="height=; width: 10px; 1px"><font class="headtext">First Name:</font><img src="/images/blank.gif" style="height=; width: 10px; 1px"><input type="text" runat="server" ID="FirstName" class="textform"></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Nickname:</td><td width="10">&nbsp;</td><td width="380" class="textform"><input type="text" runat="server" ID="Nickname" class="textform"></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Status:</td><td width="10">&nbsp;</td><td width="380" class="textform">
                <asp:DropDownList ID="StatusDropDownList" runat="server" style="width: 235px" class="textform"></asp:DropDownList></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right"></td><td width="10">&nbsp;</td><td width="380" class="textform"><input type="checkbox" runat="server" ID="isUrgent" class="headtext" onclick="enableNote();"><font class="headtext" style="color: red">Urgent  :  </font><input type="text" runat="server" ID="UrgentNote" style="width: 290px" class="textform" maxlength="40"></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Address:</td><td width="10">&nbsp;</td><td width="380" class="textform"><input type="text" runat="server" ID="Address" style="width: 367px" class="textform"></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Phone:</td><td width="10">&nbsp;</td><td width="380" class="textform"><input type="text" runat="server" ID="PhoneNumber" style="width: 200px" class="textform"></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Email:</td><td width="10">&nbsp;</td><td width="380" class="textform"><input type="text" runat="server" ID="Email" style="width: 200px" class="textform"></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Country of Birth:</td><td width="10">&nbsp;</td><td width="380" class="textform"><input type="text" runat="server" ID="CountryOfBirth" class="textform"><img src="/images/blank.gif" style="height=; width: 10px; 1px"><font class="headtext">Nationality:</font><img src="/images/blank.gif" style="height=; width: 10px; 1px"><input type="text" runat="server" ID="Nationality" class="textform"></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right" style="background-color: #CCCCCC">Emergency Contact:</td><td width="10" style="background-color: #CCCCCC">&nbsp;</td><td width="380" class="textform" style="background-color: #CCCCCC"><input type="text" runat="server" ID="EmergencyContact" style="width: 200px" class="textform"></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right" style="background-color: #CCCCCC">Emergency Address:</td><td width="10" style="background-color: #CCCCCC">&nbsp;</td><td width="380" class="textform" style="background-color: #CCCCCC"><input type="text" runat="server" ID="EmergencyAddress" style="width: 367px" class="textform"></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right" style="background-color: #CCCCCC">Emergency Number:</td><td width="10" style="background-color: #CCCCCC">&nbsp;</td><td width="380" class="textform" style="background-color: #CCCCCC"><input type="text" runat="server" ID="EmergencyNumber" style="width: 200px" class="textform"></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right" style="background-color: #CCCCCC">Emergency Email:</td><td width="10" style="background-color: #CCCCCC">&nbsp;</td><td width="380" class="textform" style="background-color: #CCCCCC"><input type="text" runat="server" ID="EmergencyEmail" style="width: 200px" class="textform"></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Program Start Date:</td><td width="10">&nbsp;</td><td width="380" class="textform"><input type="text" runat="server" ID="ProgramStartDate" style="width: 75px" maxlength="10" class="textform"><img src="/images/blank.gif" style="height=; width: 10px; 1px"><font class="headtext">Program End Date:</font><img src="/images/blank.gif" style="height=; width: 10px; 1px"><input type="text" runat="server" ID="ProgramEndDate" style="width: 75px" maxlength="10" class="textform"></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Score:</td><td width="10">&nbsp;</td><td width="380" class="textform"><input type="text" runat="server" ID="TestScoreHistory" style="width: 75px" maxlength="2" class="textform" onblur="javascript:getLevel();"><img src="/images/blank.gif"  style="height=; width: 32px; 1px;"><font class="headtext">Level:</font><img src="/images/blank.gif" style="height=; width: 10px; 1px"><asp:DropDownList ID="CurrentLevelDropDownList" runat="server" style="width: 136px" class="textform"></asp:DropDownList> </td></tr>      
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Next Tuition Date:</td><td width="10">&nbsp;</td><td class="textform"><input type="text" runat="server" ID="TuitionPaymentDate" style="width: 75px" maxlength="10" class="textform" ></td></tr>
                <tr valign="top"><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Adminstrative Notes:<br>(If any)</td><td width="10">&nbsp;</td><td width="380" class="textform"><textarea style="height=; width: 400px; 50px;" runat="server" ID="AdministrativeNotes" class="textform" ></textarea></td></tr>
                <tr valign="top"><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Student Tuition notes:<br>(If any)</td><td width="10">&nbsp;</td><td width="380" class="textform"><textarea style="height=; width: 400px; 50px;" runat="server" ID="TuitionPaymentNotes" class="textform" ></textarea></td></tr>
                <tr valign="top"><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Class Hours History:</td><td width="10">&nbsp;</td><td width="380" class="textform"><textarea style="height=; width: 400px; 50px;" runat="server" ID="ClassHoursHistory" class="textform" ></textarea></td></tr>
                <tr valign="top"><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Vacation History:</td><td width="10">&nbsp;</td><td width="380" class="textform"><textarea style="height=; width: 400px; 50px;" runat="server" ID="VacationInfo" class="textform" ></textarea></td></tr>
                <tr valign="top"><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Warning Letter Info:<br>(If any)</td><td width="10">&nbsp;</td><td width="380" class="textform"><textarea style="height=; width: 400px; 50px;" runat="server" ID="WarningLetterInfo" class="textform" ></textarea></td></tr>
                <tr valign="top"><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Comments:<br>(If any)</td><td width="10">&nbsp;</td><td width="380" class="textform"><textarea style="height=; width: 400px; 50px;" runat="server" ID="Comments" class="textform" ></textarea></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext" align="right">Image: </td><td width="10">&nbsp;</td><td width="380" class="textform"><asp:FileUpload id="StudentPic" runat="server" style="width: 300px;" class="textform"></asp:FileUpload></td></tr>
                <tr height="8"><td colspan="4"></td></tr>
                <tr><td width="10">&nbsp;</td><td width="150" class="headtext">&nbsp;</td><td width="10">&nbsp;</td><td width="380" class="textform"><asp:Button type="submit" ID="btnSubmit" Text="Submit" onserverclick="UploadBtn_Click" runat="server" style="width: 120px" class="textform"></asp:Button>&nbsp;<input type="button" ID="btnCancel" value="Cancel" style="width: 120px" class="textform" onclick=" javascript:window.parent.close(); "></td></tr>
                <tr height="8"><td colspan="4"></td></tr>
            </form>
        </table>
    </body>
</html>